[package]
name = "tiling"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
domain.workspace = true
ark-ff.workspace = true
ark-std.workspace = true
anyhow.workspace = true

[dev-dependencies]
proptest.workspace = true
